### PR TITLE
PIP Package for project files of Naarad

### PR DESCRIPTION
**Pull request by iharshit009**

### CODE REVIEW

**Comment by iharshit009** [comment]
Hi sir I have opened the PR Please have a look.

**Comment by thealphadollar** [comment]
Sure. Please resolve the issues raised by @pep8speaks

**Review by thealphadollar — CHANGES_REQUESTED** [review]
Hey @iharshit009 , Great work. I think we might go for some improvements and more learning opportunities for you.

Please add this file to the project before committing any change: https://github.com/github/gitignore/blob/master/Python.gitignore

You've included a lot of files that I think we do not need in the project code. Please have a look at the above file and reat about `.gitignore`

Also, you are doing great at learning stuff quickly. :sparkle:

**Comment by iharshit009** [comment]
sir I have made the changes and learnt many things about gitignore file but still have a doubt why we specify various files and extensions that are even not in my project files...?? 
Instead we should specify only those which are included in our project but want to ignore..

**Comment by thealphadollar** [comment]
Oh, it's actually for all python projects.

Also, in case we ever expand we won't need to update the .gitignore too
much.

**Comment by thealphadollar** [comment]
Hey @iharshit009 , thanks for adding the .gitignore file. There are still some files such as ".pyc" files which should not be committed.

Can you please remove them?

**Comment by iharshit009** [comment]
please check it out sir.

**Comment by thealphadollar** [comment]
You need to manually delete the already existing unrequired files, commit and then push.

**Comment by iharshit009** [comment]
sir i have done it.
but i wanted to know why was this step required as .gitignore should do this job..?

**Review by thealphadollar — CHANGES_REQUESTED** [review]
Delete the following files and then commit:

- naarad/dist/naarad-0.1-py3-none-any.whl
- naarad/build/scripts-3.7/naarad 
- naarad/src/naarad.egg-info/PKG-INFO
- naarad/src/naarad.egg-info/SOURCES.txt 
- naarad/src/naarad.egg-info/top_level.txt
- naarad/src/naarad.egg-info/dependency_links.txt 

It is required because you have already added and committed these files to the project and .gitignore was added later on.

**Comment by iharshit009** [comment]
and sir how to identify which to delete(include in gitignore) or not??
that means we only have to include the setup.py file and the source files for the project??

**Review by thealphadollar — APPROVED** [review]
Great work!

You seem to be learning very quickly.

**Pull request merged**
